proc dstorm_load { arg } {
}

proc dstorm_exit {} {
    global spawn_id
    if { [ catch { send "quit\n" } ignore ] } {
        fail "termination"
    } else {
        expect {
            -re "quit" { pass "termination" }
            timeout { fail "termination" }
        }
    }
}

proc dstorm_start {} {
    global DSTORM
    global spawn_id
    global verbose
    global has_debug

    if { $verbose > 1 } {
        send_user "starting $DSTORM --Twiddler\n"
    }
    spawn /usr/bin/env RAPIDSTORM_PLUGINDIR=./debug-plugin/.libs $DSTORM --Twiddler
    send "attach\n"
    expect {
        -re "attach" {}
        timeout { exit 2 }
    }
}
