/** \cond */
#ifdef INSTANTIATE_WITH_LOCALIZATION_FIELD_INDEX
INSTANTIATE_WITH_LOCALIZATION_FIELD_INDEX(0)
INSTANTIATE_WITH_LOCALIZATION_FIELD_INDEX(1)
INSTANTIATE_WITH_LOCALIZATION_FIELD_INDEX(2)
INSTANTIATE_WITH_LOCALIZATION_FIELD_INDEX(3)
INSTANTIATE_WITH_LOCALIZATION_FIELD_INDEX(4)
INSTANTIATE_WITH_LOCALIZATION_FIELD_INDEX(5)
INSTANTIATE_WITH_LOCALIZATION_FIELD_INDEX(6)
INSTANTIATE_WITH_LOCALIZATION_FIELD_INDEX(7)
#endif
/** \endcond */
