
set test "raw images output module compatible with localizations input"
set test_file "/srv/storm/ATTO655_DNA_OF2_3.txt"

if  { [file exists "$test_file"] } {

send "forSet Car forSet Method set InputMethod in Auto set InputFile value /srv/storm/ATTO655_DNA_OF2_3.txt\n"
send "forSet Car forSet Output in EngineOutput set ChooseTransmission value RawImage\n"
send "in Car set Run = 1\n"

expect {
    -re "One of your output modules needs access" { pass "$test" }
    timeout { fail "$test" }
}

} else {
    unsupported "$test"
}
