start_test_suite

dstorm_attach

set test "raw images output module compatible with localizations input"
set test_file "/srv/storm/ATTO655_DNA_OF2_3.txt"

if  { [file exists "$test_file"] } {

send "in Car in Method in InputMethod in Auto in InputFile in value set $workspace/Mikrotubuli.txt\n"
send "in Car in Output in EngineOutput in ChooseTransmission in value set RawImage\n"
untested "TIFF output module reports unwritable file correctly"
send "in Car in Output in EngineOutput in Output0 in RawImage in ToFile in value set $tmpdir/Mikrotubuli.tif\n"
send "in Car in Run in value set 1\n"

expect {
    -re "One of your output modules needs access" { pass "$test" }
    timeout { fail "$test" }
}

} else {
    unsupported "$test"
}
end_test_suite
