begin_test_suite
load_default_config
send "in Car in AutoTerminate in value set true\n"
set timeout 20

set test "Do not overwrite own input file"
send "in Car in Method in InputMethod in Auto set InputFile in value set /srv/storm/ATTO655_DNA_OF2_3.txt\n"
send "in Car in Method in InputMethod in Auto in LastImage in value set 20\n"
send "in Car in Run in value set 1\n"
expect {
    -re "failed:.*was used by multiple outputs"
        { pass "$test" }
}

dstorm_attach

set timeout -1
set test "Write file if output is changed"
set output_file "test-txt-output.txt"
send "in Car in Output in EngineOutput in Output3 in LocalizationFilter in Output0 in Table in ToFile in value set $output_file\n"
send "in Car in Run in value set 1\n"
expect {
    -re "failed:.*was used by multiple outputs" { fail "$test" }
        "\nremove dStormJob" { pass "$test" }
        "\nin dStormJob" { puts "Continuing"; exp_continue }
}
set test "Written output file exists"
if { [file exists "$output_file"] == 1 } {
    pass "$test"
} else {
    fail "$test"
}

set test "Written output file is not empty"
set filestream [open "$output_file" r]
set lc 0
while {[gets $filestream line] >= 0} { incr lc }
close $filestream
if { $lc > 1 } {
    pass "$test"
    file delete -force "$output_file"
} else {
    fail "$test"
}


wait_for_jobs

end_test_suite
