set test "SIGTERM shutdown"

send "forSet Car forSet Method set InputMethod value AndorDirectConfig\n"
send "forSet Car forSet Method in InputMethod in AndorDirectConfig in CamControl in Initialization in Initialization set ConnectToCamera = 1\n"
send "forSet Car forSet Method in InputMethod in AndorDirectConfig in CamControl in Initialization in Temperature set Cooling = true\n"

set timeout 5
set can_do_test 0
expect {
    -re "Camera is in danger zone" { set can_do_test 1 }
    -re "Could not perform action" { unsupported "$test" }
    timeout { unsupported "$test" }
}

if { $can_do_test == 1 } {
sleep 3

set storm_pid [ exp_pid ]
exec kill $storm_pid
expect {
    -re "Camera is out of danger zone" { pass "$test" }
    eof { fail "$test" }
}
}
