set test "Localization filter works"
send "attach\n"
send "in Car in Method set InputMethod in Auto in InputFile in value set ${workspace_target}Mikrotubuli.sif\n"
send "in Car in Output set EngineOutput in ChooseTransmission in value set LocalizationFilter\n"
send "in Car in Output set EngineOutput in Output0 in LocalizationFilter in ChooseTransmission in value set Image\n"
send "in Car in Output set EngineOutput in Output0 set LocalizationFilter in Output0 in Image in ShowOutput in value set true\n"
send "in Car in Output in EngineOutput in Output0 in LocalizationFilter in Output0 in Image in CloseOnCompletion in value set true\n"
send "in Car in Run in value set 1\n"

set job ""
expect  {
    -re "in (dStormJob\[0-9\]*) declare Object\r*\nname EngineStatus" { set job $expect_out(1,string); pass "$test"; }
}
sleep 1
if { $job != "" } {
    set stopped 0;
    set timeout 1
    send "in $job in EngineStatus in EngineStopper in value set 1\n"
    expect {
        -re "\nremove $job" { set stopped 1; }
        timeout {}
    }
    set timeout 10
    if { $stopped == 0 } {
        send "in $job in CloseJob in value set 1\n"
        expect {
            -re "\nremove $job" { pass "$test" }
        }
    }
}

