load_lib "dejagnu.exp"

spawn "./testSimparm"

send "attach\n"
send "in ChoiceName in value set BN\n"
send "in ChoiceName in value set Set\n"
send "in ChoiceName in Set set StringName in value set \n"
send "in ChoiceName in Set set StringName in value set foo\n"

set test "I/O processor is declared"
expect -re "desc set I/O processor" { pass "$test" ; }
set test "ChoiceName declared"
expect -re "declare ChoiceEntry\r*\nname ChoiceName" { pass "$test" ; }
