begin_test_suite
clear_tmp_dir
load_default_config
dstorm_attach

set input_file Mikrotubuli.sif
set test "Fall e) Punkt 1"
if { [file exists "${tmpdir_host}$input_file"] != 1 } {
    file link -hard "${tmpdir_host}$input_file" "${workspace_host}$input_file" 
}
set test "Fall e) Punkt 2"
send "in Car in Method in InputMethod in value set AndorSIF\n"
set test "Fall e) Punkt 3"
send "in Car in Method in InputMethod in AndorSIF in InputFile in value set $tmpdir_target$input_file\n"
set test "Fall e) Punkt 4"
send "in Car in Output in EngineOutput in Output0 in Table in ToFile in value set ${tmpdir_target}other-raw.txt\n"
send "in Car in Output in EngineOutput in Output3 in LocalizationFilter in Output0 in Table in ToFile in value set ${tmpdir_target}other.txt\n"
send "in Car in Output in EngineOutput in Output3 in LocalizationFilter in Output1 in Image in ToFile in value set ${tmpdir_target}other.jpg\n"
set test "Fall e) Punkt 5"
send "in Car in Output in EngineOutput in ChooseTransmission in value set RawImage\n"
set test "Fall e) Punkt 6"
send "in Car in Output in EngineOutput in ChooseTransmission in value set Image\n"
send "in Car in Output in EngineOutput in Output3 in LocalizationFilter in ChooseTransmission in value set Table\n"
set test "Fall e) Punkt 7"
send "in Car in Output in EngineOutput in Output3 in LocalizationFilter in ToRemove in value set Output2\n"
set test "Fall e) Punkt 8"
send "in Car in Run in value set 1\n"

set test "Job finishes for Fall e)"
expect {
    -re "in Progress in value set 0" { exp_continue }
    -re "in Progress in value set 1" { pass "$test" }
}

sleep 1

foreach file [list "other-raw.txt" "other.txt"] {
    set test "Output file $file exists"
    if { [ file exists "${tmpdir_host}$file" ] } {
        pass "$test"
    } else {
        fail "$test"
    }

    set test "Output file $file has over 100 lines"

    if { [ file exists "${tmpdir_host}$file" ] } {
        set linecount 0
        set filestream [open "${tmpdir_host}$file" r]
        while {[gets $filestream line] >= 0} {
            if { [string index $line 0] != "#" } { incr linecount }
        }
        close $filestream
        if { $linecount > 100 } {
            pass "$test"
        } else {
            fail "$test"
        }
    } else {
        fail "$test"
    }
}

set test "Output JPG image exists"
if { [ file exists "${tmpdir_host}other.jpg" ] } {
    pass "$test"
} else {
    fail "$test"
}
set test "Output JPG image 2 exists"
if { [ file exists "${tmpdir_host}Mikrotubuli.jpg" ] } {
    pass "$test"
} else {
    fail "$test"
}
set test "Output TIF image exists"
if { [ file exists "${tmpdir_host}Mikrotubuli.tif" ] } {
    pass "$test"
} else {
    fail "$test"
}

end_test_suite
