begin_test_suite
clear_tmp_dir
load_default_config
dstorm_attach

set input_file Mikrotubuli.tif
set test "Fall b) Punkt 1"
if { [file exists "${tmpdir_host}$input_file"] != 1 } {
    file link -hard "${tmpdir_host}$input_file" "${workspace_host}$input_file" 
}
set test "Fall b) Punkt 2"
send "in Car in Method in InputMethod in value set TIFF\n"
set test "Fall b) Punkt 3"
send "in Car in Method in InputMethod in TIFF in InputFile in value set $tmpdir_target$input_file\n"
set test "Fall b) Punkt 4"
send "in Car in Run in value set 1\n"

set test "Job finishes for Fall b)"
expect {
    -re "in Progress in value set 0" { exp_continue }
    -re "in LocalizationCount in value set" { exp_continue }
    -re "in Progress in value set 1" { pass "$test" }
}

sleep 1

foreach suffix [list "-raw.txt" ".txt"] {
    set test "Output file $suffix exists"
    if { [ file exists "${tmpdir_host}Mikrotubuli$suffix" ] } {
        pass "$test"
    } else {
        fail "$test"
    }

    set test "Output file $suffix has over 100 lines"

    if { [ file exists "${tmpdir_host}Mikrotubuli$suffix" ] } {
        set linecount 0
        set filestream [open "${tmpdir_host}Mikrotubuli$suffix" r]
        while {[gets $filestream line] >= 0} {
            if { [string index $line 0] != "#" } { incr linecount }
        }
        close $filestream
        if { $linecount > 100 } {
            pass "$test"
        } else {
            fail "$test"
        }
    } else {
        fail "$test"
    }
}

set test "Output JPG image exists"
if { [ file exists "${tmpdir_host}Mikrotubuli.jpg" ] } {
    pass "$test"
} else {
    fail "$test"
}

end_test_suite
