begin_test_suite
load_default_config

set timeout 150

send "in Car in Input in BiplaneSplitter set DualView value set Horizontally\n"
set_input_file "${testcase_target}2-20110413_20110407_MT-Al647-700_adjratio_300mM-MEA_Dich710_UV_0.tif"
send "in Car in Input set MultiChannel in Channels in Channel1 in InputMethod in FileMethod set FileType in TIFF set IgnoreLibtiffWarnings value set true\n"
send "in Car in Input set MultiChannel in Channels in Channel1 in InputMethod in FileMethod set FileType in TIFF set DetermineFileLength value set true\n"
send "in Car in Input in OutputBasename in Basename in value set ${tmpdir_target}2-20110413_20110407_MT-Al647-700_adjratio_300mM-MEA_Dich710_UV_0\n"
set_last_image 100
send "in Car in Input in SampleInfo set FluorophoreCount value set 2\n"
send "in Car in Engine in rapidSTORM in GuessAmplitudeThreshold in value set false\n"
send "in Car set Engine in rapidSTORM set AmplitudeThreshold in value set 3000\n"
send "in Car set Engine in rapidSTORM set SpotFindingMethod value set Median\n"
send "in Car set Engine in rapidSTORM set SpotFittingMethod in GUF set TwoKernelFitting value set false\n"
send "in Car set Engine in rapidSTORM set SpotFittingMethod in GUF set LaempiPosition value set true\n"
send "in Car set Engine in rapidSTORM set SpotFittingMethod in GUF set LaempiAmplitudes value set true\n"

dstorm_attach

send "in Car set Run value set 1\n"
set job [get_job_number]

set timeout -1
set test "Andre job 1 gets more than 0 localizations"
expect {
    -re "in LocalizationCount in value set \[1-9\]" { pass "$test"; }
    -re "Error fetching data for field \"Tag 50839\"\r*\nseverity set Error" { xfail "Strange TIFF tags can be read in Windows"; }
}
set test "Andre job 1 finishes"
expect {
    -re "in $job in.*in Progress in value set 1\r*\n" { pass "$test"; }
    -re "in LocalizationCount in value set" { exp_continue; }
    -re "in Progress in value set 0" { exp_continue; }
}
set test "Andre job 1 can be closed"
send "in $job in CloseJob in value set 1\n"
expect {
    -re "in $job in.*in Progress in value set 1" { fail "$test"; }
    -re "remove $job" { pass "$test"; }
}

end_test_suite
