
begin_test_suite
send "in Car in Input in MultiChannel set ChannelCount value set 2\n"
send "in Car in Input in MultiChannel in Channels in Channel1 set InputMethod in FileMethod set InputFile value set ${testcase_target}X5365_COS7_tetraspecksk6_ex488_256_1.tif\n"
send "in Car in Input in MultiChannel in Channels in Channel2 set InputMethod in FileMethod set InputFile value set ${testcase_target}X6069_COS7_tetraspecksk6_ex488_256_1.tif\n"
send "in Car in Input in OutputBasename set Basename value set ${tmpdir_target}negative-alignment\n"
send "in Car in Input in Optics in InputLayer1 in Alignment in value set AffineProjection\n"
send "in Car in Input in Optics in InputLayer1 in Alignment in AffineProjection in AlignmentFile value set ${testcase_target}negative-alignment\n"
send "in Car in Output in EngineOutput in ChooseTransmission in value set Count\n"

dstorm_attach
send "in Car in Run in value set 1\n"
set job_number [get_job_number]

set test "Negative alignment can be used"
expect {
    -re "in LocalizationCount in value set" { pass "$test"; }
}

end_test_suite
