begin_test_suite

dstorm_attach

send "in Car in Input in MultiChannel in ChannelCount in value set 2\n"
send "in Car in Output in EngineOutput in ChooseTransmission in value set Cache\n"
send "in Car in Output in EngineOutput in ChooseTransmission in value set Progress\n"
send "in Car in Output in EngineOutput in Output0 in Cache in ChooseTransmission in value set Image\n"
send "in Car in Output in EngineOutput in Output0 in Cache in ChooseTransmission in value set Table\n"
send "in Car in Output in EngineOutput in ChooseTransmission in value set Count\n"
send "in Car in Output in EngineOutput in Output1 in Progress in RemoveOutput in value set 1\n"
send "in Car in Output in EngineOutput in ChooseTransmission in value set Table\n"
send "in Car in Output in EngineOutput in Output3 in Table in ToFile in value set foobar\n"
send "in Car in Output in EngineOutput in ChooseTransmission in value set Expression\n"
send "in Car in Output in EngineOutput in Output4 in Expression in ExpressionCount in value set 4\n"
send "in Car in Output in EngineOutput in ChooseTransmission in value set Progress\n"

set test "Serialization throws no errors"
send "cmd 0 serialize ${tmpdir_target}serialization.txt\n"
expect {
    -re "ack 0" { pass "$test"; }
}

set test "Serialization is completed"
wait_for_file "${tmpdir_host}serialization.txt"
pass_if [file exists "${tmpdir_host}serialization.txt"] "$test"

send "reset\ncmd 0 localization\n"; expect "ack 0"; 

load_config_file "${tmpdir_host}serialization.txt"

set test "Output tree is replicated"
send "in Car in Output in EngineOutput in Output2 in Table in ToFile in value query\n"
expect {
    -re "in value value set foobar\r*\n" { pass "$test"; }
}

end_test_suite
