dstorm_start

set test "output exception at start"
send "forSet Car forSet Method set InputMethod in Auto set InputFile value /srv/storm/ATTO655_DNA_OF2_3.sif\n"
after 100
send "in Car in Output in EngineOutput set ChooseTransmission = Exception\n"
send "in Car in Output in EngineOutput in Output0 in Exception set OnConstruction = true\n"
send "in Car set Run = 1\n"
expect {
    -re "Starting job failed" { pass "$test" }
    timeout { fail "$test" }
    eof { fail "$test" }
}

set test "output exception at announcement"
send "in Car in Output in EngineOutput in Output0 in Exception set OnConstruction = false\n"
send "in Car in Output in EngineOutput in Output0 in Exception set OnAnnouncement = true\n"
send "in Car set Run = 1\n"
expect {
    -re "failed. Reason: Test Exception" { pass "$test" }
    timeout { fail "$test" }
    eof { fail "$test" }
}

set test "output exception at image 3"
send "in Car in Output in EngineOutput in Output0 in Exception set OnAnnouncement = false\n"
send "in Car in Output in EngineOutput in Output0 in Exception set OnImageNumber = 3\n"
send "in Car set Run = 1\n"
expect {
    -re "Error in computation: Test Exception" { pass "$test" }
    timeout { fail "$test" }
    eof { fail "$test" }
}
