dstorm_start
set test "segfault"
send "forSet Car forSet Method set InputMethod in Auto set InputFile value /srv/storm/ATTO655_DNA_OF2_3.sif\n"
after 100
send "in Car in Output in EngineOutput set ChooseTransmission = SegFault\n"
send "in Car in Output in EngineOutput in Output0 in SegFault set OnConstruction = true\n"
send "in Car set Run = 1\n"
expect {
    -re "Started run" { fail "$test" }
    -re "what().*Segmentation fault." { xfail "$test" }
    timeout { fail "$test" }
    eof { fail "$test" }
}
