start_test_suite
set timeout 6

set test "filename clash between two tables"
send "in Car in Method set InputMethod in Auto in InputFile in value set /srv/storm/ATTO655_DNA_OF2_3.sif\n"
send "in Car in Output in EngineOutput in ChooseTransmission in value set Table\n"
send "in Car in Output in EngineOutput in ChooseTransmission in value set Table\n"

send "in Car in Run in value set 1\n"
expect {
    -re "Starting job failed:.* output file .* was used by multiple.*" { pass "$test" }
    timeout { fail "$test" }
}

dstorm_attach

set test "filename clash between two different outputs"
send "in Car in Output in EngineOutput set ToRemove in value set Output0\n"
send "in Car in Output in EngineOutput set ChooseTransmission in value set Image\n"
set test "Image output is created"
expect {
    -re "in Car in Output in EngineOutput declare Object\r*\nname (\[A-Za-z0-9\]*)\r*\n" 
        { pass "$test"; set imageOutput $expect_out(1,string) }
}

send "in Car in Output in EngineOutput in $imageOutput in Image in ToFile in value set /srv/storm/ATTO655_DNA_OF2_3.txt\n"
send "in Car in Run in value set 1\n"
expect {
    -re "Starting job failed: The output file name '.*' was used by multiple" 
	{ pass "$test" }
}

set test "clash between input and output file name"
send "in Car in Output in EngineOutput set ToRemove in value set $imageOutput\n"
send "in Car in Output in EngineOutput in Output1 in Table in ToFile in value set /srv/storm/ATTO655_DNA_OF2_3.sif\n"
send "cmd 0 in Car in Run in value set 1\n"

expect {
   -re "Starting job failed: The output file name '.*' was used by multiple"
	 { pass "$test" }
}

end_test_suite
